services:
  frontend:
    container_name: library_manager_frontend
    build: ./fe
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    container_name: library_manager_backend
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=group34
      - CELERY_BROKER_URL=amqp://rabbitmq
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=it4409
      - POSTGRESQL_DBNAME=library_db
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
    depends_on:
      database: 
        condition: service_healthy
      message_queue:
        condition: service_healthy

  database:
    container_name: library_manager_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=it4409
      - POSTGRES_DB=library_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  message_queue:
    container_name: library_manager_message_queue
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5
